### PR TITLE
docs(README): Add basic infos about the project

### PR DESCRIPTION
**Pull request by ff6347**

### CODE REVIEW

**Comment by ff6347** [comment]
@all-contributors please update @ff6347 for docs

**Comment by Jaszkowic** [comment]
@ff6347 I would approve this, but I am not able to submit a review. Can you give me write access to this repository?

**Comment by ff6347** [comment]
> @ff6347 I would approve this, but I am not able to submit a review. Can you give me write access to this repository?

@Jaszkowic how about now?

**Review by Jaszkowic — APPROVED** [review]

**Comment by Jaszkowic** [comment]
works, thanks

**Pull request merged**
